# This is a docker-compose file for Nextcloud 26 and MariaDB 10.7.3
# Specifically, this is configured to my liking
# Volumes and Variables are not generic, so change them to your liking

version: "3"

volumes:
  nextcloud:

services:
  mariadb:
    image: mariadb:10.7.3-focal
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /AppData/nextcloud/mariadb:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=false
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud:26
    hostname: hostname
    restart: always
    ports:
      - "8080:80"
    volumes:
      # This is for Preview Generator and Recognize
      - type: tmpfs
        target: /tmp:exec
      - /AppData/nextcloud/html/:/var/www/html
      - /AppData/nextcloud/data:/srv/nextcloud/data
    labels:
      - com.centurylinklabs.watchtower.enable=false
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: mariadb
      PHP_MEMORY_LIMIT: 1024M
    # Install Imagick and start nextcloud
    command: >
      bash -c "apt-get update
      && DEBIAN_FRONTEND=noninteractive apt-get install -yq libmagickcore-6.q16-6-extra nano
      && DEBIAN_FRONTEND=noninteractive apt-get clean
      && rm -rf /var/lib/apt/lists/*
      && apache2-foreground"

networks:
  default:
    driver: bridge
